#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the happyLadybugs function below.
def happyLadybugs(b):
    for a in set(b):
        if a!='_' and b.count(a)==1:
            return 'NO'

    if '_' not in b:
        for i in range(1, len(b)):
            if b[i-1]!=b[i] and b[i+1]!= b[i]:
                return 'NO'
    return 'YES'

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    g = int(input())

    for g_itr in range(g):
        n = int(input())

        b = input()

        result = happyLadybugs(b)

        fptr.write(result + '\n')

    fptr.close()
